
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - qdrant
